{{- if .Values.ingressEnabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: pipeline-nginx
  name: {{ template "fullname" . }}
spec:
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
        path: /
{{- if .Values.secondHost }}
  - host: {{ .Values.secondHost }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
        path: /
{{- end }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: {{ .Values.secret }}
{{- if .Values.secondHost }}
  - hosts:
    - {{ .Values.secondHost }}
    secretName: {{ .Values.secondSecret }}
{{- end }}
{{- end }}