apiVersion: v1
kind: Pod
metadata:
  name: "{{.Release.Name}}-expect-to-succeed"
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: "{{.Release.Name}}-smoke-test"
      image: "{{ .Values.images.image }}"
      command: ["sh -c 'echo logs logs logs from test-success'"]
  restartPolicy: Never